Add node?

diff --git a/Dockerfile.dind b/Dockerfile.dind
--- a/Dockerfile.dind
+++ b/Dockerfile.dind
@@ -11,45 +11,60 @@ ARG DUMB_INIT_VERSION=1.2.5
 
 RUN test -n "$TARGETPLATFORM" || (echo "TARGETPLATFORM must be set" && false)
 
-ENV DEBIAN_FRONTEND=noninteractive
-RUN apt update -y \
-    && apt install -y software-properties-common \
+USER root
+ARG DEBIAN_FRONTEND=noninteractive
+ENV INSTALLER_SCRIPTS=/virtual-environments/images/linux/scripts/installers
+ENV HELPER_SCRIPTS=/virtual-environments/images/linux/scripts/helpers
+ADD packages /packages
+RUN apt-get update \
+    && apt-get install -y \
+       curl \
+       gnupg \
+    && apt-get update \
+    && apt-get install -y software-properties-common \
+    && add-apt-repository -y ppa:longsleep/golang-backports \
     && add-apt-repository -y ppa:git-core/ppa \
-    && apt update -y \
-    && apt install -y --no-install-recommends \
-    build-essential \
-    curl \
-    ca-certificates \
-    dnsutils \
-    ftp \
-    git \
-    iproute2 \
-    iputils-ping \
-    iptables \
-    jq \
-    libunwind8 \
-    locales \
-    netcat \
-    net-tools \
-    openssh-client \
-    parallel \
-    python3-pip \
-    rsync \
-    shellcheck \
-    supervisor \
-    software-properties-common \
-    sudo \
-    telnet \
-    time \
-    tzdata \
-    unzip \
-    upx \
-    wget \
-    zip \
-    zstd \
+    && curl -f -L -o nodesource.gpg.key https://deb.nodesource.com/gpgkey/nodesource.gpg.key \
+    && apt-key add nodesource.gpg.key \
+    && echo "deb https://deb.nodesource.com/node_16.x focal main" >> /etc/apt/sources.list.d/nodesource.list \
+       build-essential \
+       ca-certificates \
+       dnsutils \
+       ftp \
+       git \
+       golang-go \
+       iproute2 \
+       iputils-ping \
+       jq \
+       libunwind8 \
+       locales \
+       netcat \
+       openssh-client \
+       parallel \
+       python3-pip \
+       rsync \
+       shellcheck \
+       sudo \
+       telnet \
+       time \
+       tzdata \
+       unzip \
+       upx \
+       wget \
+       zip \
+       zstd \
+       nodejs \
+    && git clone https://github.com/actions/virtual-environments \
+    && echo "#!/bin/bash" > $HELPER_SCRIPTS/invoke-tests.sh \
+    && chmod +x $HELPER_SCRIPTS/invoke-tests.sh \
+    && ln -s $HELPER_SCRIPTS/invoke-tests.sh /usr/local/bin/invoke_tests \
+    && for f in $(cat packages); do bash "${INSTALLER_SCRIPTS}/$f.sh"; done \
+    && bash ${INSTALLER_SCRIPTS}/dpkg-config.sh \
     && ln -sf /usr/bin/python3 /usr/bin/python \
     && ln -sf /usr/bin/pip3 /usr/bin/pip \
-    && rm -rf /var/lib/apt/lists/*
+    && rm -rf /var/lib/apt/lists/* \
+    && bash ${INSTALLER_SCRIPTS}/cleanup.sh \
+    && rm -rf virtual-environments
 
 # Runner user
 RUN adduser --disabled-password --gecos "" --uid 1000 runner \
@@ -63,19 +78,15 @@ RUN adduser --disabled-password --gecos "" --uid 1000 runner \
 RUN export ARCH=$(echo ${TARGETPLATFORM} | cut -d / -f2) \
     && if [ "$ARCH" = "arm64" ]; then export ARCH=aarch64 ; fi \
     && if [ "$ARCH" = "amd64" ] || [ "$ARCH" = "i386" ]; then export ARCH=x86_64 ; fi \
-	&& if ! curl -f -L -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${ARCH}/docker-${DOCKER_VERSION}.tgz"; then \
-		echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${ARCH}'"; \
-		exit 1; \
-	fi; \
-    echo "Downloaded Docker from https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${ARCH}/docker-${DOCKER_VERSION}.tgz"; \
-	tar --extract \
-		--file docker.tgz \
-		--strip-components 1 \
-		--directory /usr/local/bin/ \
-	; \
-	rm docker.tgz; \
-	dockerd --version; \
-	docker --version
+    && if ! curl -f -L -o docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${ARCH}/docker-${DOCKER_VERSION}.tgz"; then \
+         echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${ARCH}'"; \
+         exit 1; \
+       fi; \
+       echo "Downloaded Docker from https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${ARCH}/docker-${DOCKER_VERSION}.tgz"; \
+       tar --extract --file docker.tgz --strip-components 1 --directory /usr/local/bin/; \
+       rm docker.tgz; \
+       dockerd --version; \
+       docker --version
 
 ENV RUNNER_ASSETS_DIR=/runnertmp
 ENV HOME=/home/runner
@@ -128,3 +139,4 @@ USER runner
 
 ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]
 CMD ["startup.sh"]
+
